### ISSUE TITLE
Take username password data from authinfo.gpg file

### ISSUE THREAD

**Issue by bvk** [collarchoke/ovpn-mode#1]
Would it be possible to add support for using authentication data from authinfo.gpg so that users can use complicated passwords made up of random hexadecimal strings, etc.

**Comment by anticomputer** [comment]
I'll look into supporting a 'configname.ovpn' based authinfo.gpg 'host' entry to pull user/pass for a given ovpn config. On any user/password prompts I can then present the option to feed a pulled username or pass (respectively) to the user. I don't want to fully automate it because there is ambiguity in which prompts are presented for auth based on server configs and client versions, which would require actively maintaining a prompt match that differentiates between the various inputs possible (2fa, username, password, etc.) for all the varieties of prompts. I'll think on this a bit and a push a patch when I figure out the cleanest way to support this.

**Comment by anticomputer** [comment]
I've supported the default OpenVPN user/pass prompts for transparent authinfo integration. It expects a authinfo entry that looks like: 

`machine CONFIG.OVPN login USER password PASS`

There are some new customizable variables that control this behavior:

`ovpn-mode-authinfo-path` A string that is the path to authinfo data
 `ovpn-mode-check-authinfo` A boolean that toggles authinfo checking on/off

I'll update the README in a bit.

**Comment by bvk** [comment]
I do not know much about 2FA with openvpn, so I am not sure how it works.  Otherwise, openvpn command seem to support non-interactive username/password using `--auth-user-pass`, so we don't need to manually parse openvpn output for text based username/password prompts.

I am fine with current approach in either case. Thanks :)
