### ISSUE TITLE
Running on startup

### ISSUE THREAD

**Issue by Parakovsky** [collarchoke/ovpn-mode#6]
This would be useful, probably my emacs knowledge is too limited but how it would be possible/what should be added to init file in order to ovpn automatically connect to the VPN on startup?

**Comment by anticomputer** [comment]
Currently not possible due to UI decisions, but not hard to add. I'll add some interactive functions that can take a path to a conf file to start/stop directly. Then you can just add calls to those functions to your emacs init if there's ovpn's you want to auto-run on emacs start. They will still show up as normal using the 'active' overview listing. Going to be a few days because I'm pretty swamped at work right now, will close this issue when done.

**Comment by Parakovsky** [comment]
Thank you very much, this is well appreciated!

**Comment by anticomputer** [comment]
The latest version in master has 2 new functions which you can call from elisp to start/stop a specific conf, so now you can do something like:

```
(require 'ovpn-mode)

(ovpn-mode-start-vpn-conf "/path/to/some/openvpn.ovpn")

```
This function takes an optional "with-namespace" argument, so if you want to start the vpn in a namespace just call:

`(ovpn-mode-start-vpn-conf "/path/to/some/openvpn.ovpn" t)`

These vpns will be loaded into the ovpn-mode hash-table as per usual, so they will show up when you press `a` in ovpn-mode for an active vpn overview and they will also be marked as active with the correct status if you happen to set the `d` base to their base directory. You can then interact with them in the usual ways from the mode itself.

To stop a vpn you can do something like:

`(ovpn-mode-stop-vpn-conf "/path/to/some/openvpn.ovpn")`

You can call this without concern even if the vpn was already stopped previously, it will simply not find the active process in the hash-table and gracefully error out.

There is now also a new customizable variable: `ovpn-mode-ipv6-auto-toggle`, when set to t this will automatically toggle IPv6 support to off when starting a vpn, instead of prompting for it.

Combined, this should give you all you need to start/stop vpns on emacs startup/shutdown automatically.
